import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import { useState, useEffect } from "react";
import { BsSearch } from "react-icons/bs";
import Weather from "./componets/Weather";
import Spinner from "./componets/Spinner";

export default function Home() {
  const [city, setCity] = useState("Yerevan");
  const [weather, setWeather] = useState({});
  const [loading, setLoding] = useState(false);
  const [chenger, setChenger] = useState(0);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=595d1816d9608a8ef59aa8c91ee4f196`;

  const feachWeather = () => {
    setLoding(true);
    axios.get(url).then((response) => {
      setWeather(response.data);
      setLoding(false);
    });
  };

  useEffect(() => {
    feachWeather();
  }, [chenger]); // Empty dependency array means this effect will run once when the component mounts

  const handleSubmit = (e) => {
    e.preventDefault();
    feachWeather();
    setCity("");
  };

  if (loading) {
    return <Spinner />;
  } else {
    return (
      <div className="relative flex flex-col">
        <Head>
          <title></title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* Overlay */}
        <div className="absolute top-0 left-0 right-0 bottom-0 bg-black/25 z-[1]" />
        {/* Background */}

        <Image
          src={
            "https://images.unsplash.com/photo-1580193769210-b8d1c049a7d9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=874&q=80"
          }
          layout="fill"
          className="object-cover"
        />
        {/* Search */}

        <div className="relative flex justify-betwenn item-center max-w-[500px] w-full m-auto pt-4 text-white z-10">
          <form
            onSubmit={handleSubmit}
            className="flex justify-between items-center w-full m-auto p-3 bg-transparent border border-t-gray-300 text-white rounded-2xl"
          >
            <div>
              <input
                onChange={(e) => setCity(e.target.value)}
                className="bg-transparent border-none text-white focus:outline-none text-3xl "
                type="text"
                placeholder="Search City"
              />
            </div>
            <button onClick={handleSubmit}>
              <BsSearch size={30} />
            </button>
          </form>
        </div>

        {/*Weather*/}

        {weather.main && <Weather data={weather} />}
        <div className="absolute top-[500px] left-[500px] z-10 space-x-14 text-white font-bold ">
          <button
            onClick={() => {
              setCity("Yerevan");
              setChenger(1);
            }}
            className="bg-black bg-opacity-50 text-white py-2 px-4 rounded hover:text-yellow-500"
          >
            Yerevan
          </button>
          <button
            onClick={() => {
              setCity("Moscow");
              setChenger(2);
            }}
            className="bg-black bg-opacity-50 text-white py-2 px-4 rounded hover:text-yellow-500"
          >
            Moscow
          </button>
          <button
            onClick={() => {
              setCity("Los Angeles");
              setChenger(3);
            }}
            className="bg-black bg-opacity-50 text-white py-2 px-4 rounded hover:text-yellow-500"
          >
            Los Angeles
          </button>
          <button
            onClick={() => {
              setCity("Paris");
              setChenger(4);
            }}
            className="bg-black bg-opacity-50 text-white py-2 px-4 rounded hover:text-yellow-500"
          >
            Paris
          </button>
        </div>
      </div>
    );
  }
}
